[package]
name = "mozdef_proxy"
version = "0.1.0"
authors = ["Emma Rose <emrose@mozilla.com>"]
edition = "2018"

[dependencies]
chrono = { version = "^0.4", features = ["serde"] }
clap = "^2.32"
env_logger = "^0.6"
iron = "^0.6"
log = "^0.4"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
