service: mozdef-proxy

provider:
  name: aws
  runtime: rust
  region: ${opt:region, 'us-west-2'}
  stackName: mozdef-proxy-deploy
  apiName: mozdef-proxy-ap
  environment:
    BIND_ADDRESS: ${opt:bind-to, '0.0.0.0:80'}
    SQS_QUEUE_NAME: ${opt:queue}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource: "arn:aws:sqs:${self:provider.region}::${opt:queue}"

package:
  individually: true

functions:
  main:
    handler: mozdef-proxy
    events:
      - http:
          path: /
          method: POST

plugins:
  - serverless-rust