service: mozdef-proxy

provider:
  name: aws
  runtime: rust
  region: ${opt:region, 'us-west-2'}
  stackName: mozdef-proxy-deploy
  apiName: mozdef-proxy-api
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource: "arn:aws:sqs:${self:provider.region}::${opt:queue}"

plugins:
  - serverless-rust

package:
  individually: true

functions:
  main:
    handler: mozdef-proxy
    events:
      - http:
          path: /
          method: POST
