# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: mozdef-proxy

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: rust

plugins:
  - serverless-rust

package:
  individually: true

# The `functions` block defines what code to deploy
functions:
  main:
    handler: mozdef-proxy
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: /
          method: POST
